# Generated by Django 3.1.2 on 2020-11-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(default='no-mans-land'),
        ),
        migrations.AddField(
            model_name='account',
            name='pii',
            field=models.TextField(default='12345'),
        ),
    ]
